#!/usr/bin/env bash
set -Eeuo pipefail

# Reconstruct two LaTeX manuscripts from source/, committing one top-level
# section at a time. Each intermediate file remains compilable.

readonly SOURCE_DIR="source"
readonly FILES=(
  "consensus-without-independence.tex"
  "latency-of-evidence.tex"
)

force=0
push_each=0
dry_run=0

usage() {
  printf '%s\n' \
    "Usage: $0 [--force] [--push-each] [--dry-run]" \
    "" \
    "  --force      Replace existing root copies of the two manuscripts." \
    "  --push-each  Push after every commit instead of once at the end." \
    "  --dry-run    Show the planned commits without changing anything."
}

while (($#)); do
  case "$1" in
    --force) force=1 ;;
    --push-each) push_each=1 ;;
    --dry-run) dry_run=1 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

command -v git >/dev/null || { printf 'git is required.\n' >&2; exit 1; }
command -v gh >/dev/null || { printf 'gh is required.\n' >&2; exit 1; }
git rev-parse --show-toplevel >/dev/null 2>&1 || {
  printf 'Run this inside a Git repository.\n' >&2
  exit 1
}

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

gh auth status >/dev/null 2>&1 || {
  printf 'GitHub CLI is not authenticated; run: gh auth login\n' >&2
  exit 1
}
gh repo view >/dev/null 2>&1 || {
  printf 'This repository is not connected to a GitHub repository.\n' >&2
  exit 1
}

if [[ -n $(git status --porcelain) ]]; then
  printf 'The worktree is not clean. Commit or stash existing changes first.\n' >&2
  exit 1
fi

for file in "${FILES[@]}"; do
  [[ -f "$SOURCE_DIR/$file" ]] || {
    printf 'Missing source file: %s/%s\n' "$SOURCE_DIR" "$file" >&2
    exit 1
  }
  if [[ -e "$file" && $force -eq 0 ]]; then
    printf 'Target already exists: %s (use --force to replace it)\n' "$file" >&2
    exit 1
  fi
done

work_dir=$(mktemp -d)
trap 'rm -rf -- "$work_dir"' EXIT

# Split at un-commented top-level \section or starred \section commands.
# Chunk 0 contains the complete front matter through the text immediately
# before the first section. The source's final \end{document} is removed and
# supplied afresh to every generated snapshot.
split_tex() {
  local input=$1 out_dir=$2
  mkdir -p "$out_dir"
  awk -v dir="$out_dir" '
    function path() { return sprintf("%s/%04d.tex", dir, chunk) }
    /^[[:space:]]*\\section\*?([[:space:]]*\{|\[)/ { chunk++ }
    /^[[:space:]]*\\end\{document\}[[:space:]]*(%.*)?$/ { next }
    { print >> path(); close(path()) }
  ' "$input"
}

section_title() {
  local chunk=$1 fallback=$2
  local title
  title=$(sed -nE 's/^[[:space:]]*\\section\*?(\[[^]]*\])?\{([^}]*)\}.*/\2/p' "$chunk" | head -n 1)
  printf '%s' "${title:-$fallback}"
}

commit_snapshot() {
  local message=$1
  shift
  if ((dry_run)); then
    printf 'Would commit: %s\n' "$message"
    return
  fi
  git add -- "$@"
  git diff --cached --quiet && {
    printf 'No change for planned commit: %s\n' "$message" >&2
    return
  }
  git commit -m "$message"
  if ((push_each)); then
    git push
  fi
}

for file in "${FILES[@]}"; do
  split_tex "$SOURCE_DIR/$file" "$work_dir/$file"
done

# Establish both manuscripts together, including their preambles and front
# matter, so neither disappears from later commits.
if ((dry_run == 0)); then
  for file in "${FILES[@]}"; do
    cp "$work_dir/$file/0000.tex" "$file"
    printf '\\end{document}\n' >> "$file"
  done
fi
commit_snapshot "Add manuscript front matter" "${FILES[@]}"

# Add one section per commit, alternating manuscripts while both still have
# sections remaining. This makes the repository history grow both papers
# together rather than completing one before beginning the other.
round=1
while :; do
  added=0
  for file in "${FILES[@]}"; do
    chunk=$(printf '%s/%s/%04d.tex' "$work_dir" "$file" "$round")
    [[ -f "$chunk" ]] || continue
    added=1
    title=$(section_title "$chunk" "section $round")
    if ((dry_run == 0)); then
      # Remove only the terminator generated by this script.
      sed -i '${/^\\end{document}$/d;}' "$file"
      sed -e '${/^\\end{document}[[:space:]]*$/d;}' "$chunk" >> "$file"
      printf '\\end{document}\n' >> "$file"
    fi
    stem=${file%.tex}
    commit_snapshot "Expand ${stem}: ${title}" "$file"
  done
  ((added)) || break
  ((round += 1))
done

if ((dry_run)); then
  printf 'Dry run complete. No files or commits were changed.\n'
  exit 0
fi

if ((push_each == 0)); then
  git push
fi

printf 'Completed monotonic reconstruction and pushed all commits.\n'

