PDF = papers/beyond-optimal-foraging/beyond-optimal-foraging.pdf

pdf:
	cd papers/beyond-optimal-foraging && xelatex -interaction=nonstopmode beyond-optimal-foraging.tex

clean:
	rm -f papers/beyond-optimal-foraging/*.aux \
	      papers/beyond-optimal-foraging/*.log \
	      papers/beyond-optimal-foraging/*.out \
	      papers/beyond-optimal-foraging/*.toc

.PHONY: pdf clean
