use anyhow::{Context, Result};
use std::process::{Command, Stdio};
use std::io::Write;
use std::time::{Duration, Instant};

pub struct RunResult {
    pub output: String,
    pub duration_secs: f64,
    pub used_mock: bool,
}

/// Invoke the configured backend on an assembled prompt. `runner` is
/// "ollama" or "mock". Falls back to the mock backend (with a warning on
/// stderr) if the requested runner's binary can't be found, so the whole
/// pipeline stays runnable on a machine without local models installed.
pub fn run(runner: &str, model: &str, full_prompt: &str, _timeout_secs: u64) -> Result<RunResult> {
    let start = Instant::now();
    match runner {
        "mock" => Ok(mock_run(full_prompt, start)),
        "ollama" => {
            if which("ollama").is_none() {
                eprintln!("[zebra] warning: 'ollama' not found on PATH, falling back to mock backend");
                return Ok(mock_run(full_prompt, start));
            }
            run_ollama(model, full_prompt, start)
        }
        other => anyhow::bail!("unknown backend runner '{other}' (expected 'ollama' or 'mock')"),
    }
}

fn mock_run(full_prompt: &str, start: Instant) -> RunResult {
    let preview: String = full_prompt.chars().take(400).collect();
    let output = format!(
        "<!-- mock backend output: no model was actually invoked -->\n\n\
         # Mock artifact\n\n\
         This is a placeholder artifact generated by Zebra's mock backend.\n\
         It stands in for whatever a real model would have produced from\n\
         the assembled prompt below, so the pipeline can be exercised without\n\
         a local model installed.\n\n\
         ## Prompt preview (first 400 chars)\n\n```\n{preview}\n```\n"
    );
    RunResult { output, duration_secs: elapsed(start), used_mock: true }
}

fn run_ollama(model: &str, full_prompt: &str, start: Instant) -> Result<RunResult> {
    let mut child = Command::new("ollama")
        .arg("run")
        .arg(model)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .with_context(|| "failed to spawn 'ollama run'")?;

    if let Some(stdin) = child.stdin.as_mut() {
        stdin
            .write_all(full_prompt.as_bytes())
            .context("writing prompt to ollama stdin")?;
    }

    let out = child.wait_with_output().context("waiting on ollama process")?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        anyhow::bail!("ollama exited with an error: {stderr}");
    }
    let output = String::from_utf8_lossy(&out.stdout).to_string();
    Ok(RunResult { output, duration_secs: elapsed(start), used_mock: false })
}

fn elapsed(start: Instant) -> f64 {
    let d: Duration = start.elapsed();
    d.as_secs_f64()
}

fn which(bin: &str) -> Option<String> {
    let path_var = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path_var) {
        let candidate = dir.join(bin);
        if candidate.is_file() {
            return Some(candidate.to_string_lossy().to_string());
        }
    }
    None
}
